MODEL:
  TYPE: swinunetr
  NAME: swin_unetr_btcv_pretrain
  NUM_CLASSES: 3
  PRETRAINED: '/home/data/temp/model_swin_unetr_btcv_segmentation_v1.pt'
  RESUME: ''
  DROP_RATE: 0.0
  DROP_PATH_RATE: 0.1
  LABEL_SMOOTHING: 0.1
  SWIN_UNETR:
    IN_CHANNELS: 1
    OUT_CHANNELS: 14
    IMG_SIZE:
    - 96
    - 96
    - 96
    FEATURE_SIZE: 48
    PATCH_SIZE: 2
    DEPTHS:
    - 2
    - 2
    - 4
    - 2
    SPATIAL_DIMS: 3
    USE_CHECKPOINT: true
DATA:
  IMG_SIZE: 224
  DEPTH_SIZE: 64
  BATCH_SIZE: 2
  NUM_WORKERS: 4
  PIN_MEMORY: true
  CACHE_MODE: part
  ZIP_MODE: false
  INTERPOLATION: bicubic
  DATASET: biglunge
  DATA_PATH: ''
  MASK_PATCH_SIZE: 32
  MASK_RATIO: 0.6
TRAIN:
  USE_CHECKPOINT: false
  EPOCHS: 100
  BASE_LR: 0.0001
  WARMUP_EPOCHS: 10
  WARMUP_LR: 0.0001
  MIN_LR: 5.0e-06
  WEIGHT_DECAY: 0.05
  CLIP_GRAD: 1.0
  ACCUMULATION_STEPS: 4
  AUTO_RESUME: true
  START_EPOCH: 0
  LR_SCHEDULER:
    NAME: cosine
    DECAY_EPOCHS: 30
    DECAY_RATE: 0.1
    GAMMA: 0.1
    MULTISTEPS: []
    WARMUP_PREFIX: true
  OPTIMIZER:
    NAME: adamw
    EPS: 1.0e-08
    BETAS:
    - 0.9
    - 0.999
    MOMENTUM: 0.9
  MOE:
    SAVE_MASTER: false
AMP_ENABLE: true
AMP_OPT_LEVEL: ''
ENABLE_AMP: false
FUSED_LAYERNORM: false
FUSED_WINDOW_PROCESS: false
LOCAL_RANK: 0
OUTPUT: output/swin_unetr
TAG: default
SEED: 42
EVAL_MODE: false
THROUGHPUT_MODE: false
PRINT_FREQ: 10
SAVE_FREQ: 1
TEST:
  CROP: true
  SEQUENTIAL: false
  SHUFFLE: false
AUG:
  COLOR_JITTER: 0.4
  AUTO_AUGMENT: rand-m9-mstd0.5-inc1
  REPROB: 0.25
  REMODE: pixel
  RECOUNT: 1
  MIXUP: 0.0
  CUTMIX: 0.0
  CUTMIX_MINMAX: null
  MIXUP_PROB: 1.0
  MIXUP_SWITCH_PROB: 0.5
  MIXUP_MODE: batch
BASE:
- ''
